### ISSUE TITLE
Example given in the README not working

### ISSUE THREAD

**Issue by jollyjonson** [jaakkopasanen/ABX#10]
Hi,
first of all: Thanks for that great piece of open source software, love it! I've seemingly encountered a small issue:
The example given in the `README.md` seems to be broken, when clicking on the link

https://abxtests.com/?test=https://www.dropbox.com/s/c00dylhi7ekqkfw/demo.yml?dl=0

it just shows a blank screen. I've checked the YAML formatting and whether all audio links are valid, no problems in that regard. Maybe you want to investigate this further :)

**Comment by faroit** [comment]
I guess dropbox changed their api

**Comment by jaakkopasanen** [comment]
I guess this has not worked in over 2 years 🙈 

The format of the demo YML file was incorrect. I uploaded a new file and it works now.
