### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by Pluckerpluck** [jaakkopasanen/ABX#9]
> In case you want to host ABX app your self, say you have some super secret and important test to conduct, you can do that easily too. You'll find the details on how to deploy your own ABX app in a docker container in no time. It's all open source!

The above sentence on the web page implies that I can freely take and modify this code as I see fit. I would love to do this, as I want to take some of what it does, and expand upon it.

**However,** the code doesn't come with a license. Which means, legally, I can't do that. At least, not if I ever want to share it with anyone ever. So can you please either clarify your position here, or add a license file. I much prefer the fully open ones myself (e.g. MIT) but it's your choice.

--------

Side note: I'm awfully lazy and never finish projects. So I may never even actually do this. But without a license I definitely can't start!

**Comment by jaakkopasanen** [comment]
Hey. Thanks a lot for reporting, I totally forgot to add the licence. But now the problem has been fixed and you'll find the project being licenced under [MIT licence](https://github.com/jaakkopasanen/ABX/blob/master/LICENCE).
